#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#


namespace: multimodal-sample-app
# Please provide docker registry details below for docker images pull/push operations.
# Please provide full registry url with port trail by /
# e.q. localhost:5000/
DOCKER_REGISTRY: ''
DOCKER_USERNAME: ''
DOCKER_PASSWORD: ''
imagePullPolicy: IfNotPresent
storageClassName: manual
env:
  # The INFLUXDB_USERNAME must contain only alphabets and be at least 5 characters minimum
  # Do not set INFLUXDB_USERNAME to 'admin'.
  INFLUXDB_USERNAME: 

  # The INFLUXDB_PASSWORD length must be a minimum of 10 alphanumeric characters with at least one digit
  # Do not use the following special characters in the INFLUXDB_PASSWORD "~:'+[/@^{%(-"*|,&<`}._=}!>;?#$)\"
  INFLUXDB_PASSWORD: 

  # The VISUALIZER_GRAFANA_USER must contain only alphabets and be at least 5 characters minimum
  VISUALIZER_GRAFANA_USER: 

  # The VISUALIZER_GRAFANA_PASSWORD length must be a minimum of 10 alphanumeric characters with at least one digit
  VISUALIZER_GRAFANA_PASSWORD: 

  # If your environment requires a proxy to access external resources, please set the following variables.
  # If no proxy is required, please leave them empty.
  HTTP_PROXY: 
  HTTPS_PROXY: 
  
  # If CONTINUOUS_SIMULATOR_INGESTION is set to true (default), continuous looping of simulator data is enabled.
  # To ingest the simulator data only once (without looping), set this variable to false.
  CONTINUOUS_SIMULATOR_INGESTION: true
  TELEGRAF_INPUT_PLUGIN: mqtt_consumer
  TIMESERIES_USER_NAME: timeseries_user
  TIMESERIES_UID: 1999
  TIMESERIES_NO_PROXY: influxdb,ia-time-series-analytics-microservice,mqttbroker,ia-mqtt-broker,ia-opcua-server 
  # For proxy environment, please append IP addresses or Range IP addresses of each node of the cluster to no_proxy
  # e.q. timeseries_no_proxy=localhost,127.0.0.1,10.223.109.130,10.223.109.170
  timeseries_no_proxy: localhost,127.0.0.1,.intel.com
  # The InfluxDB retention policy durations can be configured using a combination of time units such as hours(h), minutes(m), and seconds(s), eg., 1h0m0s for 1 hour.
  INFLUXDB_RETENTION_DURATION: 1h0m0s
  # The Telegraf metric_batch_size specifies the number of metrics or data points that are grouped together and sent in a single batch to the InfluxDB.
  TELEGRAF_METRIC_BATCH_SIZE: 100
  LOG_LEVEL: INFO
  # Weld Data Simulator config
  TS_TOPIC: weld-data
  SIMULATION_TARGET_FPS: 10

  ## DL Streamer Pipeline Server
  # HOST_IP is the IP address of server where DLStreamer Pipeline Server is running
  HOST_IP: 
  REST_SERVER_PORT: 8080
  RTSP_CAMERA_IP: mediamtx

  # Open Telemetry related config
  ENABLE_OPEN_TELEMETRY: false
  OTEL_COLLECTOR_HOST: otel-collector
  OTEL_COLLECTOR_PORT: 4318
  OTEL_EXPORT_INTERVAL_MILLIS: 5000
  PROMETHEUS_PORT: 9999

  # Webrtc related config
  # mediamtx-port for streaming
  WHIP_SERVER_PORT: 8889
  MTX_WEBRTCICESERVERS2_0_USERNAME: 
  MTX_WEBRTCICESERVERS2_0_PASSWORD: 
  COTURN_UDP_PORT: 3478

  # Fusion Analytics config
  FUSION_MODE: OR
  TOLERANCE_NS: "50e6"
gpu:
  enabled: false
  type: "gpu.intel.com/i915"
  count: 1
images:
  # Please provide the suffix for the image version you want to use like rc1, rc2, git hash id etc.
  image_suffix: "weekly"
  time_series_analytics_image: intel/ia-time-series-analytics-microservice:1.1.0
  opcua_server_image: intel/ia-opcua-server:1.0.0
  mqtt_publisher_image: intel/ia-mqtt-publisher:1.1.0
  weld_data_simulator_image: intel/ia-weld-data-simulator:1.0.0
  dlstreamer_pipeline_server: intel/dlstreamer-pipeline-server:3.1.0-ubuntu24
  fusion_analytics_image: intel/ia-multimodal-fusion-analytics:1.0.0
privileged_access_required: false
config:
  influx_db_server:
    name: influxdb
    influx_http: 8086
  grafana:
    name: ia-grafana
    grafana_port: "3000"
  telegraf:
    name: telegraf
    MQTT_BROKER_HOST: "ia-mqtt-broker"
  time_series_analytics_microservice:
    name: ia-time-series-analytics-microservice
    kapacitor_port: 9092
  time_series_analytics_microservice_rest_api:
    name: time-series-analytics-microservice-rest-api
    rest_api_port: 5000
  mqttbroker:
    name: ia-mqtt-broker
    mqttbroker_port: 1883
  nginx:
    name: nginx
    int:
      https_port: "15443"
      mqtt_port: "1883"
    ext:
      https_port: "30001"
      mqtt_port: "30002"
  mediamtx:
    name: mediamtx
    int:
      webrtc_port: "8889"
      rtsp_port: "8554"
    ext:
      rtsp_port: "31111"
      webrtc_port: "31112"
  dlstreamer_pipeline_server:
    name: dlstreamer-pipeline-server
    int:
      rest_api_port: "8080"
      rtsp_output_port: "8554"

  coturn:
    name: coturn
    int:
      coturn_tcp_port: "3478"
      coturn_udp_port: "3478"
    ext:
      coturn_tcp_port: "30478"
      coturn_udp_port: "30478"
volumes:
  pipelines:
    name: vol-pipelines
    size: 100Mi
    location: "/home/pipeline-server/pipelines"
    hostpath: "/opt/intel/eii/pipelines"