# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "wsgd"
displayName: "wsgd"
description: "Worker Safety Gear Detection Deployment Package"
version: "1.0.0"

applications:
  - name: wsgd-app
    version: 1.0.0

defaultNamespaces:
  wsgd-app: wsgd

deploymentProfiles:
  - name: "default"
    description: "Uses CPU for inferencing"
    applicationProfiles:
      - application: "wsgd-app"
        profile: "default"
  - name: "with-intel-gpu"
    description: "Uses Intel GPU for inferencing, needs Intel GPU extension"
    applicationProfiles:
      - application: "wsgd-app"
        profile: "with-intel-gpu"