#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.mqttbroker.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: ia-mqtt-broker
  ports:
    - name: broker-port
      port: {{ .Values.config.mqttbroker.mqttbroker_port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ia-mqtt-broker
  name: deployment-mqtt-broker
  namespace: {{ .Values.namespace }}

spec:
  selector:
    matchLabels:
      app: ia-mqtt-broker
  template:
    metadata:
      labels:
        app: ia-mqtt-broker
    spec:
      containers:
      - name: ia-mqtt-broker
        image: eclipse-mosquitto:2.0.21
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          runAsUser: {{ $.Values.env.TIMESERIES_UID }}
          runAsGroup: {{ $.Values.env.TIMESERIES_UID }}
          readOnlyRootFilesystem: true 
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: mosquitto-conf
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf

      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto-conf