#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.nginx.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: https
    port: {{ $.Values.config.nginx.int.https_port }}
    targetPort: {{ $.Values.config.nginx.int.https_port }}
    nodePort: {{ $.Values.config.nginx.ext.https_port }}
  - name: mqtt
    port: {{ $.Values.config.nginx.int.mqtt_port }}
    targetPort: {{ $.Values.config.nginx.int.mqtt_port }}
    nodePort: {{ $.Values.config.nginx.ext.mqtt_port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: deployment-nginx
  namespace: {{ .Values.namespace }}

spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-proxy
        image: nginx:1.29.1-bookworm-perl
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          runAsUser: {{ $.Values.env.TIMESERIES_UID }}
          runAsGroup: {{ $.Values.env.TIMESERIES_UID }}
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        command: ["/bin/bash", "-c", "/usr/local/bin/nginx-cert-gen.sh && exec nginx -g 'daemon off;'"]
        env:
        - name: no_proxy
          value: "ia-grafana,ia-time-series-analytics-microservice,ia-mqtt-broker,{{ .Values.env.timeseries_no_proxy }},coturn,mediamtx,{{ .Values.env.HOST_IP }},dlstreamer-pipeline-server"
        - name: NO_PROXY
          value: "ia-grafana,ia-time-series-analytics-microservice,ia-mqtt-broker,{{ .Values.env.timeseries_no_proxy }},coturn,mediamtx,{{ .Values.env.HOST_IP }},dlstreamer-pipeline-server"
        - name: HOST_IP
          value: "{{ .Values.env.HOST_IP }}"
        - name: WHIP_SERVER_PORT
          value: "{{ .Values.config.mediamtx.ext.webrtc_port }}"
        volumeMounts:
        - name: nginx-conf
          mountPath: /tmp/default.conf.template
          subPath: nginx.conf
        - name: nginx-cert-gen
          mountPath: /usr/local/bin/nginx-cert-gen.sh
          subPath: nginx-cert-gen.sh
        - name: vol-temp-nginx
          mountPath: /opt/nginx/certs
        - name: vol-temp-nginx
          mountPath: /var/cache/nginx
        - name: vol-temp-nginx
          mountPath: /run
        - name: vol-temp-nginx
          mountPath: /etc/nginx/
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: nginx-cert-gen
        configMap:
          name: nginx-cert-gen
          defaultMode: 0705
      - name: vol-temp-nginx
        emptyDir: {}
