---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Pre-Merge CI Pipeline

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

permissions: {}

jobs:
  filter:
    permissions:
      contents: read          # needed for actions/checkout
    runs-on: ubuntu-latest
    outputs:
      hmi-augmented-worker_changed: ${{ steps.filter.outputs.hmi-augmented-worker }}
      image-based-video-search_changed: ${{ steps.filter.outputs.image-based-video-search }}
      industrial-edge-insights-time-series_changed: ${{ steps.filter.outputs.industrial-edge-insights-time-series }}
      loitering-detection_changed: ${{ steps.filter.outputs.loitering-detection }}
      metro-sdk-manager_changed: ${{ steps.filter.outputs.metro-sdk-manager }}
      pallet-defect-detection_changed: ${{ steps.filter.outputs.pallet-defect-detection }}
      pcb-anomaly-detection_changed: ${{ steps.filter.outputs.pcb-anomaly-detection }}
      robotics-ai-suite_changed: ${{ steps.filter.outputs.robotics-ai-suite }}
      smart-intersection_changed: ${{ steps.filter.outputs.smart-intersection }}
      smart-parking_changed: ${{ steps.filter.outputs.smart-parking }}
      visual-search-question-and-answering_changed: ${{ steps.filter.outputs.visual-search-question-and-answering }}
      weld-porosity_changed: ${{ steps.filter.outputs.weld-porosity }}
      worker-safety-gear-detection_changed: ${{ steps.filter.outputs.worker-safety-gear-detection }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set paths filter
        id: filter
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        with:
          filters: |
            hmi-augmented-worker:
              - 'manufacturing-ai-suite/hmi-augmented-worker/docs/**'
            image-based-video-search:
              - 'metro-ai-suite/image-based-video-search/docs/**'
            industrial-edge-insights-time-series:
              - 'manufacturing-ai-suite/industrial-edge-insights-time-series/docs/**'
            loitering-detection:
              - 'metro-ai-suite/metro-vision-ai-app-recipe/loitering-detection/docs/**'
            metro-sdk-manager:
              - 'metro-ai-suite/metro-sdk-manager/docs/**'
            pallet-defect-detection:
              - 'manufacturing-ai-suite/industrial-edge-insights-vision/apps/pallet-defect-detection/docs/**'
            pcb-anomaly-detection:
              - 'manufacturing-ai-suite/industrial-edge-insights-vision/apps/pcb-anomaly-detection/docs/**'
            robotics-ai-suite:
              - 'robotics-ai-suite/docs/**'
            smart-intersection:
              - 'metro-ai-suite/metro-vision-ai-app-recipe/smart-intersection/docs/**'
            smart-parking:
              - 'metro-ai-suite/metro-vision-ai-app-recipe/smart-parking/docs/**'
            visual-search-question-and-answering:
              - 'metro-ai-suite/visual-search-question-and-answering/docs/**'
            weld-porosity:
              - 'manufacturing-ai-suite/industrial-edge-insights-vision/apps/weld-porosity/docs/**'
            worker-safety-gear-detection:
              - 'manufacturing-ai-suite/industrial-edge-insights-vision/apps/worker-safety-gear-detection/docs/**'

  build_hmi-augmented-worker:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.hmi-augmented-worker_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: manufacturing-ai-suite/hmi-augmented-worker
      exclude_patterns: "**user-guide/overview.md"

  build_image-based-video-search:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.image-based-video-search_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: metro-ai-suite/image-based-video-search

  build_industrial-edge-insights-time-series:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.industrial-edge-insights-time-series_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: manufacturing-ai-suite/industrial-edge-insights-time-series
      exclude_patterns: "**/Overview.md"

  build_loitering-detection:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.loitering-detection_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: metro-ai-suite/metro-vision-ai-app-recipe/loitering-detection

  build_metro-sdk-manager:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.metro-sdk-manager_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: metro-ai-suite/metro-sdk-manager

  build_pallet-defect-detection:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.pallet-defect-detection_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: manufacturing-ai-suite/industrial-edge-insights-vision/apps/pallet-defect-detection
      exclude_patterns: "**user-guide/Overview.md"

  build_pcb-anomaly-detection:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.pcb-anomaly-detection_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: manufacturing-ai-suite/industrial-edge-insights-vision/apps/pcb-anomaly-detection
      exclude_patterns: "**user-guide/Overview.md"

  build_robotics-ai-suite:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.robotics-ai-suite_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: robotics-ai-suite
      simple_mode: false

  build_smart-intersection:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.smart-intersection_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: metro-ai-suite/metro-vision-ai-app-recipe/smart-intersection

  build_smart-parking:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.smart-parking_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: metro-ai-suite/metro-vision-ai-app-recipe/smart-parking

  build_visual-search-question-and-answering:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.visual-search-question-and-answering_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: metro-ai-suite/visual-search-question-and-answering
      exclude_patterns: "**user-guide/Overview.md"

  build_weld-porosity:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.weld-porosity_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: manufacturing-ai-suite/industrial-edge-insights-vision/apps/weld-porosity
      exclude_patterns: "**user-guide/Overview.md"

  build_worker-safety-gear-detection:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.worker-safety-gear-detection_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: manufacturing-ai-suite/industrial-edge-insights-vision/apps/worker-safety-gear-detection
      exclude_patterns: "**user-guide/Overview.md"
